config/routes.rb
Rails.application.routes.draw do

  resources :films, :cinemas do
     resources :seances
  end

  

  get 'home/index'
  root 'home#index'
  post 'films/:id/like' => 'films#send_like'
  get 'films/:id/likes' => 'films#show_likes'

end

app/models/seance.rb
class Seance < ActiveRecord::Base
	attr_accessible :heure, :film_id, :cinema_id
	belongs_to :cinema
	belongs_to :film
end

app/controllers/seances_controller.rb
class SeancesController < ApplicationController
  before_action :set_seance, only: [:show, :edit, :update, :destroy]
  before_filter :load_cinema, :load_film

  # GET /seances
  # GET /seances.json
  def index
    if params[:cinema_id]
      @seance = @cinema.seances.all
    elsif params[:film_id]
      @seance = @film.seances.all
    end

  end

  # GET /seances/1
  # GET /seances/1.json
  def show
    if params[:cinema_id]
      @seance = @cinema.seances.find(params[:id])
    elsif params[:film_id] 
      @seance = @film.seances.find(params[:id])
    end
  end

  # GET /seances/new
  def new
    if params[:cinema_id]
      @seance = @cinema.seances.new
    elsif params[:film_id]
      @seance = @film.seances.new
    end

  end

  # GET /seances/1/edit
  def edit
    if params[:cinema_id]
      @seance = @cinema.seances.find(params[:id])
    elsif params[:film_id]
      @seance = @film.seances.find(params[:id])
    end
  end

  # POST /seances
  # POST /seances.json
  def create
    if params[:cinema_id]
      @seance= @cinema.seances.new(params[:seance])
        respond_to do |format|
          if @seance.save
            format.html { redirect_to [@cinema, @seance], notice: 'Seance was successfully created.' }
            format.json { render :show, status: :created, location: @seance }
          else
            format.html { render :new }
            format.json { render json: @seance.errors, status: :unprocessable_entity }
          end
        end
    elsif params[:film_id]
      @seance= @film.seances.new(params[:seance])
        respond_to do |format|
          if @seance.save
            format.html { redirect_to [@film, @seance], notice: 'Seance was successfully created.' }
            format.json { render :show, status: :created, location: @seance }
          else
            format.html { render :new }
            format.json { render json: @seance.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # PATCH/PUT /seances/1
  # PATCH/PUT /seances/1.json
  def update
    if params[:cinema_id]
      @seance= @cinema.seances.find(params[:id])
        respond_to do |format|
          if @seance.update(seance_params)
            format.html { redirect_to [@cinema, @seance], notice: 'Seance was successfully updated.' }
            format.json { render :show, status: :ok, location: @seance }
          else
            format.html { render :edit }
            format.json { render json: @seance.errors, status: :unprocessable_entity }
          end
        end
    elsif params[:film_id]
      @seance= @film.seances.find(params[:id])
        respond_to do |format|
          if @seance.update(seance_params)
            format.html { redirect_to [@film, @seance], notice: 'Seance was successfully updated.' }
            format.json { render :show, status: :ok, location: @seance }
          else
            format.html { render :edit }
            format.json { render json: @seance.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # DELETE /seances/1
  # DELETE /seances/1.json
  def destroy
    if params[:cinema_id]
      @seance = @cinema.seances.find(params[:id])
      @seance.destroy
      respond_to do |format|
        format.html { redirect_to cinema_seances_path(@cinema)}
        format.json { head :no_content }
      end
    elsif params[:film_id]
      @seance = @film.seances.find(params[:id])
      @seance.destroy
      respond_to do |format|
        format.html { redirect_to film_seances_path(@film)}
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seance
      @seance = Seance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seance_params
      params.require(:seance).permit(:heure, :film_id, :cinema_id)
    end
    
    def load_film
      if params[:film_id]
        @film = Film.find(params[:film_id])
      end
    end

    def load_cinema
      if params[:cinema_id]
        @cinema = Cinema.find(params[:cinema_id])
        end
    end
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/views/seances/_form.html.erb
<% if params[:cinema_id] %>
  <%= form_for [@cinema,@seance], :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :heure, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :heure, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :film_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :film_id, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :cinema_id, :class => 'control-label' %>
      <div class="controls">
        <%= @seance.cinema_id %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  cinema_seances_path(@cinema), :class => 'btn' %>
    </div>
  <% end %>
<% elsif params[:film_id] %>
  <%= form_for [@film,@seance], :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :heure, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :heure, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :film_id, :class => 'control-label' %>
      <div class="controls">
        <%= @seance.film_id %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :cinema_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :cinema_id, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  film_seances_path(@film), :class => 'btn' %>
    </div>
  <% end %>
<% end %>

app/views/seances/edit.html.erb
<h1>Editing seance</h1>

<%= render 'form' %>


<%= if params[:cinema_id] 
  		link_to 'Show', cinema_seance_path(@cinema,@seance)
  		link_to 'Back', cinema_seances_path(@cinema)
 	elsif params[:film_id] 
 		link_to 'Show', film_seance_path(@film,@seance)
 		link_to 'Back', film_seances_path(@film)

 end %>

app/views/seances/index.html.erb
<%- model_class = Seance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:heure) %></th>
      <th><%= model_class.human_attribute_name(:film_id) %></th>
      <th><%= model_class.human_attribute_name(:cinema_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if params[:cinema_id] %>
      <% @cinema.seances.each do |seance| %>
        <tr>
          <td><%= link_to seance.id, cinema_seance_path(@cinema, seance) %></td>
          <td><%= seance.heure %></td>
          <td><img src="<%= Film.find(seance.film_id).affiche %>" style="width:100px" /></td> </td>
          <td><%= Cinema.find(params[:cinema_id]).ville %>
              ,
              <%= Cinema.find(params[:cinema_id]).nom %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cinema_seance_path(@cinema, seance), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cinema_seance_path(@cinema, seance),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% elsif params[:film_id] %>
      <% @film.seances.each do |seance| %>
        <tr>
          <td><%= link_to seance.id, film_seance_path(@film, seance) %></td>
          <td><%= seance.heure %></td>
          <td><img src="<%= Film.find(params[:film_id]).affiche %>" style="width:300px" /></td>
          <td><%= Cinema.find(seance.cinema_id).ville %>
              ,
              <%= Cinema.find(seance.cinema_id).nom %>
          </td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_film_seance_path(@film, seance), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      film_seance_path(@film, seance),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<% if params[:cinema_id] %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_cinema_seance_path(@cinema),
            :class => 'btn btn-primary'%>
   <% elsif params[:film_id] %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_film_seance_path(@film),
            :class => 'btn btn-primary'%>
   <% end%>
    

app/views/seances/new.html.erb
<%- model_class = Seance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/seances/show.html.erb
<%- model_class = Seance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<% if params[:cinema_id] %>
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:heure) %>:</strong></dt>
    <dd><%= @seance.heure %></dd>
    <dt><strong><%= model_class.human_attribute_name(:film_id) %>:</strong></dt>
    <dd> <iframe width="560" height="315" src="<%= Film.find(@seance.film_id).BO %>" frameborder="0" allowfullscreen></iframe></dd>
    <dt><strong><%= model_class.human_attribute_name(:cinema_id) %>:</strong></dt>
    <dd><iframe src="<%= Cinema.find(@seance.cinema_id).adresse %>" width="560" height="315" frameborder="0" style="border:0"></iframe></dd>
  </dl>
<% elsif params[:film_id] %>
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:heure) %>:</strong></dt>
    <dd><%= @seance.heure %></dd>
    <dt><strong><%= model_class.human_attribute_name(:film_id) %>:</strong></dt>
    <dd><%= Film.find(params[:film_id]).titre %></dd>
    <dt><strong><%= model_class.human_attribute_name(:cinema_id) %>:</strong></dt>
    <dd><iframe src="<%= Cinema.find(@seance.cinema_id).adresse %>" width="600" height="450" frameborder="0" style="border:0"></iframe></dd>
  </dl>
<% end %>
<div class="form-actions">
  <% if params[:cinema_id] %>
    <%= link_to t('.back', :default => t("helpers.links.back")),
              cinema_seances_path(@cinema), :class => 'btn'  %>
    <%=link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cinema_seance_path(@cinema, @seance), :class => 'btn' %>
    <%=link_to t('.destroy', :default => t("helpers.links.destroy")),
              cinema_seance_path(@cinema, @seance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% elsif params[:film_id]%>
    <%=link_to t('.back', :default => t("helpers.links.back")),
              film_seances_path(@film), :class => 'btn'  %>
    <%=link_to t('.edit', :default => t("helpers.links.edit")),
              edit_film_seance_path(@film, @seance), :class => 'btn' %>
    <%=link_to t('.destroy', :default => t("helpers.links.destroy")),
              film_seance_path(@film, @seance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>