config/routes.rb
Rails.application.routes.draw do

  resources :films, :cinemas do
     resources :seances
  end

  

  get 'home/index'
  root 'home#index'
  post 'films/:id/like' => 'films#send_like'
  get 'films/:id/likes' => 'films#show_likes'

end

app/models/film.rb
class Film < ActiveRecord::Base
	attr_accessible :titre, :realisateur, :acteurs, :BO, :synopsis, :datesortie,:affiche
	has_many :seances
	has_many :likes
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy, :send_like, :show_likes]

  skip_before_action :verify_authenticity_token, only: [:send_like]
  # GET /films
  # GET /films.json
  def index
    @films = Film.all 
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

#definition du like
  def send_like
    # On crée un nouvel objet booking à partir des paramètres reçus
    @other_likes=@film.likes
    @like = Like.new(like_params)
    # On précise que cet object Booking dépend du show concerné
    @like.film = @film
     puts YAML::dump(@like)

    respond_to do |format|
      if @like.save
        format.json
      else
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_likes
    @likes= @film.likes
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @likes}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:titre, :realisateur, :acteurs, :BO, :synopsis, :datesortie,:affiche)
    end

    def like_params
      params.require(:like).permit(:user_name)
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for @film, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :titre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :realisateur, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :realisateur, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :acteurs, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :acteurs, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :BO, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :BO, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :synopsis, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :synopsis, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :datesortie, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :datesortie, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                films_path, :class => 'btn' %>
  </div>
<% end %>

app/views/films/edit.html.erb
<%- model_class = Film -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/films/index.html.erb
<%- model_class = Film -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titre) %></th>
      <th><%= model_class.human_attribute_name(:realisateur) %></th>
      <th><%= model_class.human_attribute_name(:acteurs) %></th>
      <th><%= model_class.human_attribute_name(:affiche) %></th>
      <th><%= model_class.human_attribute_name(:datesortie) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= link_to film.id, film_path(film) %></td>
        <td><%= film.titre %></td>
        <td><%= film.realisateur %></td>
        <td><%= film.acteurs %></td>
        <td><img src="<%= film.affiche %>" style="width:300px" /></td>
        <td><%= film.datesortie %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_film_path(film), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      film_path(film),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_film_path,
            :class => 'btn btn-primary' %>

app/views/films/new.html.erb
<%- model_class = Film -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/films/show.html.erb
<%- model_class = Film -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titre) %>:</strong></dt>
  <dd><%= @film.titre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:realisateur) %>:</strong></dt>
  <dd><%= @film.realisateur %></dd>
  <dt><strong><%= model_class.human_attribute_name(:acteurs) %>:</strong></dt>
  <dd><%= @film.acteurs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:BO) %>:</strong></dt>
  <iframe width="560" height="315" src="<%= @film.BO %>" frameborder="0" allowfullscreen></iframe>
  <dt><strong><%= model_class.human_attribute_name(:synopsis) %>:</strong></dt>
  <dd><%= @film.synopsis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:datesortie) %>:</strong></dt>
  <dd><%= @film.datesortie %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              films_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_film_path(@film), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              film_path(@film),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
   <%= link_to "Seances", "/films/#{@film.id}/seances" , :class => 'btn' %>
</div>

app/views/films/show_likes.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Film id</th>
    <th>User_name</th>
    <th>Like id</th>
    <th></th>
    <th></th>
  </tr>

<% @likes.each do |like| %>
  <tr>
    <td><%= like.user_name %></td>
    <td><%= like.id %></td>
  </tr>
<% end %>
</table>

<br />