config/routes.rb
Rails.application.routes.draw do

  resources :films, :cinemas do
     resources :seances
  end

  

  get 'home/index'
  root 'home#index'
  post 'films/:id/like' => 'films#send_like'
  get 'films/:id/likes' => 'films#show_likes'

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
	attr_accessible :ville, :adresse, :seancehoraire, :nom
	has_many :seances
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  before_action :set_cinema, only: [:show, :edit, :update, :destroy]
  # GET /cinemas
  # GET /cinemas.json
  skip_before_action :verify_authenticity_token
  def index
    @cinemas = Cinema.all
  end

  # GET /cinemas/1
  # GET /cinemas/1.json
  def show
  end

  # GET /cinemas/new
  def new
    @cinema = @film.cinemas.new
  end

  # GET /cinemas/1/edit
  def edit
    @cinema = @film.cinemas.find(params[:id])  #n'y était pas avant, peut-être supprimer en temps 2

  end

  # POST /cinemas
  # POST /cinemas.json
  def create
    @cinema = Cinema.new(cinema_params)

    respond_to do |format|
      if @cinema.save
        format.html { redirect_to @cinema, notice: 'Cinema was successfully created.' }
        format.json { render :show, status: :created, location: @cinema }
      else
        format.html { render :new }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cinemas/1
  # PATCH/PUT /cinemas/1.json
  def update
    respond_to do |format|
      if @cinema.update(cinema_params)
        format.html { redirect_to @cinema, notice: 'Cinema was successfully updated.' }
        format.json { render :show, status: :ok, location: @cinema }
      else
        format.html { render :edit }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cinemas/1
  # DELETE /cinemas/1.json
  def destroy
    @cinema.destroy
    respond_to do |format|
      format.html { redirect_to cinemas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cinema
      @cinema = Cinema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cinema_params
      params.require(:cinema).permit(:ville, :adresse, :seancehoraire, :nom)
    end

end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/_form.html.erb
<%= form_for (@cinema), :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :ville, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ville, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :adresse, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :adresse, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :seancehoraire, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :seancehoraire, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nom, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cinemas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cinemas/edit.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cinemas/index.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ville) %></th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:adresse) %></th>
      <th><%= model_class.human_attribute_name(:seancehoraire) %></th>
    </tr>
  </thead>
  <tbody>
    <% @cinemas.each do |cinema| %>
      <tr>
        <td><%= link_to cinema.id, cinema_path(cinema) %></td>
        <td><%= cinema.ville %></td>
        <td><%= cinema.nom %></td>
        <td><iframe src="<%=cinema.adresse%>" width="600" height="90" frameborder="0" style="border:0"></iframe></td>
        <td><%= cinema.seancehoraire %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cinema_path(cinema), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cinema_path(cinema),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cinema_path,
            :class => 'btn btn-primary' %>

app/views/cinemas/new.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cinemas/show.html.erb
<%- model_class = Cinema -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ville) %>:</strong></dt>
  <dd><%= @cinema.ville %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nom) %>:</strong></dt>
  <dd><%= @cinema.nom %></dd>
  <dt><strong><%= model_class.human_attribute_name(:adresse) %>:</strong></dt>
<iframe src="<%=@cinema.adresse%>" width="600" height="450" frameborder="0" style="border:0"></iframe>
  <dt><strong><%= model_class.human_attribute_name(:seancehoraire) %>:</strong></dt>
  <dd><%= @cinema.seancehoraire %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cinemas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cinema_path(@cinema), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cinema_path(@cinema),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
   <%= link_to "Séances", "/cinemas/#{@cinema.id}/seances" , :class => 'btn' %>
</div>